# 1. This tells Azure Pipelines to watch your GitHub repository's main branch
trigger:
  branches:
    include:
      - main
pool:
  name: default
 
variables:
  azureServiceConnection: 'Azure-Subscription-Conn'
  acrName: 'finalproject26'
  aksCluster: 'epos'
  resourceGroup: 'final-project'
  imageName: 'epos-final-project'
 
steps:
- checkout: self  # Natively pulls down your GitHub source files
 
# 2. Log in to ACR, Build the Docker image, and Push it
- task: AzureCLI@2
  displayName: 'Build Image Directly in ACR'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr build \
        --registry $(acrName) \
        --resource-group $(resourceGroup) \
        --image $(imageName):$(Build.BuildId) \
        .

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
  displayName: 'Install unzip'
 
# 3. Securely pull down the necessary tools to communicate with AKS non-interactively
- task: KubeloginInstaller@0
  displayName: 'Install Kubelogin'
  inputs:
    kubeloginVersion: 'latest'
 
# 4. Connect to AKS and Deploy your app manifests
- task: AzureCLI@2
  displayName: 'Deploy to AKS'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials \
        --resource-group $(resourceGroup) \
        --name $(aksCluster) \
        --overwrite-existing

      kubelogin convert-kubeconfig -l azurecli

      kubectl create namespace ecom-prod --dry-run=client -o yaml | kubectl apply -f -

      sed -i "s|finalproject26.azurecr.io/epos-final-project:v1|$(acrName).azurecr.io/$(imageName):$(Build.BuildId)|g" deployment.yaml

      kubectl apply -f deployment.yaml -n ecom-prod