apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ecom-deployment
  namespace: epos-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ecom
  template:
    metadata:
      labels:
        app: flask-ecom
    spec:
      containers:
        - name: ecom-container
          image: finalproject26.azurecr.io/epos-final-project:V1
          ports:
            - containerPort: 8000
            
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: SECRET_KEY

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: DB_HOST
        
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: DB_PORT
        
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: DB_PASSWORD
            
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: AZURE_STORAGE_CONNECTION_STRING

            - name: AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: AZURE_CONTAINER_NAME

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: STRIPE_SECRET_KEY

            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: epos-app-secrets
                  key: STRIPE_WEBHOOK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: epos-final-project-service
  namespace: epos-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: flask-ecom
  externalTrafficPolicy: Local
